main: dev.skyphi.App
name: AdvancementCounter
version: 1.0
api-version: 1.19
commands:
   advcounter:
      description: Start/stop the advancement counter
      usage: /<command>
   resetadv:
      description: Reset all online players' advancement progress
      usage: /<command>
permissions:
   advcounter.*:
      description: Gives access to all Advancement-Counter commands
      default: op
      children:
         - advcounter.start
         - advcounter.reset
   advcounter.start:
      default: op
      description: Gives access to /advcounter (starts/stops the counter)
   advcounter.reset:
      default: op
      description: Gives access to /resetadv (resets all online players' advancement progress)